
/*Updating the Volume counts for declared volume for each customer(supply_chain_id) and item_id*/
UPDATE ADJUSTMENTS ADJ
SET DECLARED_VOLUME = SO.DEC_VOL
FROM (SELECT SUPPLY_CHAIN_ID,ITEM_ID,SUM(QUANTITY)AS DEC_VOL FROM SALES_ORDERS GROUP BY SUPPLY_CHAIN_ID,ITEM_ID) SO
WHERE ADJ.SUPPLY_CHAIN_ID = SO.SUPPLY_CHAIN_ID
AND SO.ITEM_ID = 1
AND ADJ.ADJ_CODE = 'LA1';

UPDATE ADJUSTMENTS ADJ
SET DECLARED_VOLUME = SO.DEC_VOL
FROM (SELECT SUPPLY_CHAIN_ID,ITEM_ID,SUM(QUANTITY)AS DEC_VOL FROM SALES_ORDERS GROUP BY SUPPLY_CHAIN_ID,ITEM_ID) SO
WHERE ADJ.SUPPLY_CHAIN_ID = SO.SUPPLY_CHAIN_ID
AND SO.ITEM_ID = 2
AND ADJ.ADJ_CODE = 'SP2';

UPDATE ADJUSTMENTS ADJ
SET DECLARED_VOLUME = SO.DEC_VOL
FROM (SELECT SUPPLY_CHAIN_ID,ITEM_ID,SUM(QUANTITY)AS DEC_VOL FROM SALES_ORDERS GROUP BY SUPPLY_CHAIN_ID,ITEM_ID) SO
WHERE ADJ.SUPPLY_CHAIN_ID = SO.SUPPLY_CHAIN_ID
AND SO.ITEM_ID = 3
AND ADJ.ADJ_CODE = 'LP3';


/*Updating the Volume counts for seen volume for each customer(bc_supply_chain_id) and bc_item_id*/
UPDATE ADJUSTMENTS ADJ
SET SEEN_VOLUME = MPC.SEEN_VOL
FROM (SELECT BC_SUPPLY_CHAIN_ID,BC_ITEM_ID,COUNT(MAIL_PIECE_ID)AS SEEN_VOL FROM MAIL_PIECE_SCANS GROUP BY BC_SUPPLY_CHAIN_ID,BC_ITEM_ID) MPC
WHERE ADJ.SUPPLY_CHAIN_ID = MPC.BC_SUPPLY_CHAIN_ID
AND MPC.BC_ITEM_ID = 1
AND ADJ.ADJ_CODE = 'LA1';

UPDATE ADJUSTMENTS ADJ
SET SEEN_VOLUME = MPC.SEEN_VOL
FROM (SELECT BC_SUPPLY_CHAIN_ID,BC_ITEM_ID,COUNT(MAIL_PIECE_ID)AS SEEN_VOL FROM MAIL_PIECE_SCANS GROUP BY BC_SUPPLY_CHAIN_ID,BC_ITEM_ID) MPC
WHERE ADJ.SUPPLY_CHAIN_ID = MPC.BC_SUPPLY_CHAIN_ID
AND MPC.BC_ITEM_ID = 2
AND ADJ.ADJ_CODE = 'SP2';

UPDATE ADJUSTMENTS ADJ
SET SEEN_VOLUME = MPC.SEEN_VOL
FROM (SELECT BC_SUPPLY_CHAIN_ID,BC_ITEM_ID,COUNT(MAIL_PIECE_ID)AS SEEN_VOL FROM MAIL_PIECE_SCANS GROUP BY BC_SUPPLY_CHAIN_ID,BC_ITEM_ID) MPC
WHERE ADJ.SUPPLY_CHAIN_ID = MPC.BC_SUPPLY_CHAIN_ID
AND MPC.BC_ITEM_ID = 3
AND ADJ.ADJ_CODE = 'LP3';


/*Updating the Adjustments volume and amount for all adjustments where positive amount indicates penalties and negative amount indicates dicounts for each customer*/
UPDATE ADJUSTMENTS
SET ADJ_VOLUME = SEEN_VOLUME - DECLARED_VOLUME;

UPDATE ADJUSTMENTS
SET ADJ_AMOUNT = ADJ_VOLUME*1.5
WHERE ADJ_VOLUME > 0;

UPDATE ADJUSTMENTS
SET ADJ_AMOUNT = 0
WHERE ADJ_VOLUME = 0;

UPDATE ADJUSTMENTS
SET ADJ_AMOUNT = ADJ_VOLUME*0.75
WHERE ADJ_VOLUME < 0;